# Generated by Django 4.2.3 on 2023-08-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_name', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_type_image', models.ImageField(blank=True, null=True, upload_to='DonationTypeImage')),
                ('donation_amount', models.FloatField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donation_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_image', models.ImageField(blank=True, null=True, upload_to='DonationHeaderImage')),
                ('donation_description', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_now_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('my_donation_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_list_header', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_list_body', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_list_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_list_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_conform_message', models.CharField(blank=True, max_length=500, null=True)),
                ('donation_failure_message', models.CharField(blank=True, max_length=500, null=True)),
                ('support_number', models.BigIntegerField(null=True)),
                ('ngo_logo', models.ImageField(blank=True, null=True, upload_to='DonationLogoImage')),
                ('ngo_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_pan', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_gstin', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_header_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_footer_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_signature_header', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_signature_image', models.ImageField(blank=True, null=True, upload_to='SignatureImage')),
                ('ngo_signature_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donation_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('receipient_pdf', models.ImageField(blank=True, null=True, upload_to='ReceipientImage')),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
