# Generated by Django 4.2.3 on 2023-08-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_settings',
            name='donation_contact_us_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation_types',
            name='donation_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
