# Generated by Django 4.2.3 on 2023-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0003_rename_email_donation_details_donar_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_details',
            name='donation_reference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation_details',
            name='payment_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
