# Generated by Django 4.2.3 on 2023-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0004_donation_details_donation_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_details',
            name='receipient_pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDFFiles'),
        ),
    ]
