# Generated by Django 4.2.3 on 2023-08-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0005_alter_donation_details_receipient_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_settings',
            name='donation_contact_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='ContactUsImage'),
        ),
    ]
