# Generated by Django 4.2.3 on 2023-08-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0006_donation_settings_donation_contact_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_details',
            name='donation_comments_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='contact_us_details_button_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='my_donation_details_button_name1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='my_donation_details_button_name2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='my_donation_details_button_name3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
