# Generated by Django 4.2.3 on 2023-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0007_donation_details_donation_comments_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_details',
            name='donar_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
