# Generated by Django 4.2.3 on 2023-11-16 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_n', '0008_alter_donation_details_donar_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_type', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_category', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_location', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_description', models.CharField(blank=True, max_length=500, null=True)),
                ('ngo_contact_number', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donation_payment_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=200, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_n.donation_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='donation_payment_gateway_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_key', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, choices=[('INR', 'Rupees'), ('USD', 'DOLLAR'), ('GBP', 'Pounds'), ('EUR', 'Euros')], max_length=200, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_n.donation_marketplace')),
            ],
        ),
        migrations.AddField(
            model_name='donation_details',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_n.donation_marketplace'),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_n.donation_marketplace'),
        ),
        migrations.AddField(
            model_name='donation_types',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_n.donation_marketplace'),
        ),
    ]
