# Generated by Django 4.2.3 on 2023-12-26 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_n', '0010_donation_ngo_type_donation_ngo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_marketplace_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('my_donation_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplace_welcome_image', models.ImageField(blank=True, null=True, upload_to='FlowImage')),
                ('marketplace_welcome_message_body', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplace_welcome_message_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('generic_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mydonation_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
