# Generated by Django 4.2.3 on 2023-12-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0011_donation_marketplace_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_marketplace',
            name='key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='donation_marketplace',
            name='ngo_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
