# Generated by Django 4.2.3 on 2024-01-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_n', '0012_donation_marketplace_key_donation_marketplace_ngo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_marketplace',
            name='ngo_link_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='donation_marketplace',
            name='ngo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='ngo_link_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='donation_settings',
            name='ngo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
