# Generated by Django 4.2.3 on 2023-09-01 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_customer_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Customer_Whatsapp_Number', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_City', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_Status', models.IntegerField(blank=True, null=True)),
                ('Customer_Address_Line1', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_Address_Line2', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_Address_Landmark', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_Address_Pincode', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_State', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_Country', models.CharField(blank=True, max_length=300, null=True)),
                ('Customer_Alternate_Number', models.CharField(blank=True, max_length=300, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='generic_campaign_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_short_message', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_message', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_Image', models.ImageField(blank=True, null=True, upload_to='CampaignImage')),
                ('Campaign_First_Button_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_Second_Button_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_Third_Button_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_Status', models.IntegerField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='generic_campaign_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_short_message', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_message', models.CharField(blank=True, max_length=300, null=True)),
                ('Campaign_Image', models.ImageField(blank=True, null=True, upload_to='CampaignImage')),
                ('Campaign_Status', models.IntegerField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('campaign_sent_datetime', models.DateTimeField(blank=True, null=True)),
                ('campaign_customer_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_customer_master')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('generic_campaign_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.generic_campaign_info')),
            ],
        ),
    ]
