# Generated by Django 4.2.3 on 2024-01-11 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_marketplace_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('my_campaign_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplace_welcome_image', models.ImageField(blank=True, null=True, upload_to='FlowImage')),
                ('marketplace_welcome_message_body', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplace_welcome_message_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('generic_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mycampaign_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='campaign_marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_type', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_category', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_location', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_description', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_contact_number', models.CharField(blank=True, max_length=300, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=300, null=True)),
                ('campaign_key', models.CharField(blank=True, max_length=300, null=True)),
                ('campaign_url', models.CharField(blank=True, max_length=300, null=True)),
                ('campaign_link_text', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='campaign_group_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_group_type', models.CharField(blank=True, max_length=200, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='campaign_group_categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_group_category', models.CharField(blank=True, max_length=200, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace')),
            ],
        ),
        migrations.AddField(
            model_name='campaign_customer_master',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace'),
        ),
        migrations.AddField(
            model_name='generic_campaign_history',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace'),
        ),
        migrations.AddField(
            model_name='generic_campaign_info',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace'),
        ),
    ]
