# Generated by Django 4.2.3 on 2024-01-20 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_b', '0002_campaign_marketplace_settings_campaign_marketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='template_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=300, null=True)),
                ('template_header_text', models.CharField(blank=True, max_length=300, null=True)),
                ('template_header_image', models.CharField(blank=True, max_length=300, null=True)),
                ('template_body_message', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='template_info_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_button_num', models.IntegerField(blank=True, null=True)),
                ('template_button_name', models.CharField(blank=True, max_length=300, null=True)),
                ('template_button_type', models.CharField(blank=True, max_length=300, null=True)),
                ('template_additional_info', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.template_info')),
            ],
        ),
        migrations.CreateModel(
            name='campaign_payment_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=200, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='campaign_payment_gateway_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_key', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, choices=[('INR', 'Rupees'), ('USD', 'DOLLAR'), ('GBP', 'Pounds'), ('EUR', 'Euros')], max_length=200, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace')),
            ],
        ),
    ]
