# Generated by Django 4.2.3 on 2024-01-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0003_template_info_template_info_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_info',
            name='template_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='TemplateImage'),
        ),
    ]
