# Generated by Django 4.2.3 on 2024-01-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0004_alter_template_info_template_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_info',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace'),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace'),
        ),
    ]
