# Generated by Django 4.2.3 on 2024-01-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0005_template_info_marketplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_info',
            name='generic_campaign_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.generic_campaign_info'),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='generic_campaign_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.generic_campaign_info'),
        ),
    ]
