# Generated by Django 4.2.3 on 2024-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0006_template_info_generic_campaign_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_info',
            name='template_header_type',
            field=models.CharField(choices=[('none', 'NONE'), ('image', 'IMAGE'), ('text', 'TEXT')], default='none', max_length=100),
        ),
    ]
