# Generated by Django 4.2.3 on 2024-02-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0007_template_info_template_header_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_info_details',
            name='template_file_path',
            field=models.FileField(blank=True, null=True, upload_to='ButtonType'),
        ),
    ]
