# Generated by Django 4.2.3 on 2024-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0008_template_info_details_template_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic_campaign_info',
            name='default_campaign',
            field=models.CharField(choices=[('none', 'NONE'), ('yes', 'YES'), ('no', 'NO')], default='none', max_length=100),
        ),
    ]
