# Generated by Django 4.2.3 on 2024-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0010_generic_campaign_history_campaign_foot_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic_campaign_history',
            name='Customer_Whatsapp_Number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
