# Generated by Django 4.2.3 on 2024-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0014_rename_name_form_form_body_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='additional_file_path1',
            field=models.FileField(blank=True, null=True, upload_to='SecondInflowType'),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='additional_file_path2',
            field=models.FileField(blank=True, null=True, upload_to='ThirdInflowType'),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='additional_info1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='additional_info2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='additional_file_path1',
            field=models.FileField(blank=True, null=True, upload_to='SecondButtonType'),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='additional_file_path2',
            field=models.FileField(blank=True, null=True, upload_to='ThirdButtonType'),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='template_additional_info1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='template_additional_info2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
