# Generated by Django 4.2.3 on 2024-03-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0016_campaign_footprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_fieldchoice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='vailodb_b.form_field'),
        ),
        migrations.AlterField(
            model_name='form_fieldchoice',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace'),
        ),
    ]
