# Generated by Django 4.2.3 on 2024-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0017_alter_form_fieldchoice_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='screen_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
