# Generated by Django 4.2.3 on 2024-03-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0019_campaign_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_marketplace_settings',
            name='master_card_template_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='template_info',
            name='template_footer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
