# Generated by Django 4.2.3 on 2024-03-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0021_campaign_group_customer_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_group',
            name='template_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.template_info'),
        ),
        migrations.AddField(
            model_name='campaign_group_customer_mapping',
            name='template_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.template_info'),
        ),
        migrations.AddField(
            model_name='generic_campaign_history',
            name='campaign_group_customer_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_group_customer_mapping'),
        ),
    ]
