# Generated by Django 4.2.3 on 2024-03-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0022_campaign_group_template_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign_group_customer_mapping',
            name='template_info',
        ),
        migrations.RemoveField(
            model_name='generic_campaign_history',
            name='campaign_group_customer_mapping',
        ),
        migrations.DeleteModel(
            name='campaign_group',
        ),
        migrations.DeleteModel(
            name='campaign_group_customer_mapping',
        ),
    ]
