# Generated by Django 4.2.3 on 2024-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0025_campaign_formdata_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_info',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('APPROVED', 'approved')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PUBLISHED', 'Published')], default='none', max_length=255),
        ),
    ]
