# Generated by Django 4.2.3 on 2024-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0026_template_info_status_alter_form_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'APPROVED')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='template_info',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'APPROVED')], default='none', max_length=255),
        ),
    ]
