# Generated by Django 4.2.3 on 2024-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0029_form1_section_field_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_formdata',
            name='form_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
