# Generated by Django 4.2.3 on 2024-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0030_campaign_formdata_form_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='Reference_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
