# Generated by Django 4.2.3 on 2024-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0031_inflow_setup_details_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow_setup_details',
            name='open_button_type',
            field=models.CharField(blank=True, choices=[('CHAIN', 'chain'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('FORM', 'form'), ('PHONE', 'phone')], max_length=200, null=True),
        ),
    ]
