# Generated by Django 4.2.3 on 2024-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0032_alter_inflow_setup_details_open_button_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic_campaign_history',
            name='message_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
