# Generated by Django 4.2.3 on 2024-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0033_generic_campaign_history_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow_setup_details',
            name='inflow_header_type',
            field=models.CharField(choices=[('none', 'NONE'), ('image', 'IMAGE'), ('text', 'TEXT')], default='none', max_length=100),
        ),
    ]
