# Generated by Django 4.2.3 on 2024-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0034_alter_inflow_setup_details_inflow_header_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow_setup_details',
            name='open_button_type',
            field=models.CharField(blank=True, choices=[('CHAIN', 'chain'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('FORM', 'form'), ('PHONE', 'phone'), ('TEXT', 'text'), ('CARDS', 'cards'), ('TITLE', 'title')], max_length=200, null=True),
        ),
    ]
