# Generated by Django 4.0.5 on 2024-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0035_alter_inflow_setup_details_open_button_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic_campaign_history',
            name='user_local_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generic_campaign_info',
            name='user_local_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template_info',
            name='user_local_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
