# Generated by Django 4.0.5 on 2024-06-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0036_generic_campaign_history_user_local_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic_campaign_history',
            name='user_local_time',
        ),
        migrations.RemoveField(
            model_name='generic_campaign_info',
            name='user_local_time',
        ),
        migrations.RemoveField(
            model_name='template_info',
            name='user_local_time',
        ),
    ]
