# Generated by Django 4.0.5 on 2024-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0037_remove_generic_campaign_history_user_local_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='child_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
