# Generated by Django 4.0.5 on 2024-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0039_alter_inflow_setup_details_open_button_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow_setup_details',
            name='open_button_type',
            field=models.CharField(blank=True, choices=[('CHAIN', 'chain'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('FORM', 'form'), ('PHONE', 'phone'), ('TEXT', 'text'), ('CARDS', 'cards'), ('TITLE', 'title'), ('URL', 'url'), ('MAIN', 'main')], max_length=200, null=True),
        ),
    ]
