# Generated by Django 4.0.5 on 2024-07-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_b', '0042_pre_inflow_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.CharField(choices=[('1', '1'), ('2', '2')], default='none', max_length=100)),
                ('card_header_type', models.CharField(choices=[('image', 'IMAGE'), ('video', 'VIDEO')], default='none', max_length=100)),
                ('carousel_button1_type', models.CharField(blank=True, max_length=300, null=True)),
                ('carousel_button1_name', models.CharField(blank=True, max_length=300, null=True)),
                ('carousel_button1_additional_info', models.CharField(blank=True, max_length=300, null=True)),
                ('carousel_button1_file_path', models.FileField(blank=True, null=True, upload_to='CardType')),
                ('carousel_button2_type', models.CharField(blank=True, max_length=300, null=True)),
                ('carousel_button2_name', models.CharField(blank=True, max_length=300, null=True)),
                ('carousel_button2_additional_info', models.CharField(blank=True, max_length=300, null=True)),
                ('carousel_button2_file_path', models.FileField(blank=True, null=True, upload_to='Card')),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('generic_campaign_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.generic_campaign_info')),
                ('template_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.template_info')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel_Cards_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_header_file_path', models.FileField(blank=True, null=True, upload_to='CardHeaderType')),
                ('card_header_body_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('carousel_cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.carousel_cards')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
