# Generated by Django 4.0.5 on 2024-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0044_language_key_language_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_info',
            name='template_header_file_path',
            field=models.FileField(blank=True, null=True, upload_to='TemplateHeaderFile'),
        ),
    ]
