# Generated by Django 4.0.5 on 2024-07-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0045_template_info_template_header_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow_setup_details',
            name='child_id',
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inflow_setup_details',
            name='open_button_type',
            field=models.CharField(blank=True, choices=[('CHAIN', 'chain'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('FORM', 'form'), ('PHONE', 'phone'), ('TEXT', 'text'), ('CARDS', 'cards'), ('TITLE', 'title'), ('URL', 'url'), ('LOCATION', 'location'), ('MAIN', 'main')], max_length=200, null=True),
        ),
    ]
