# Generated by Django 4.0.5 on 2024-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0047_alter_inflow_setup_details_inflow_header_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_field',
            name='required_type',
            field=models.CharField(choices=[('True', 'TRUE'), ('False', 'FALSE')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='location_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='location_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='template_info_details',
            name='location_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
