# Generated by Django 4.0.5 on 2024-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0049_carousel_cards_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_groups',
            name='group_type',
            field=models.CharField(blank=True, choices=[('None', 'NONE'), ('Private', 'PRIVATE'), ('Public', 'PUBLIC')], max_length=100, null=True),
        ),
    ]
