# Generated by Django 4.0.5 on 2024-07-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0050_campaign_groups_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_key',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language_value',
            name='auto_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template_info_details',
            name='template_button_type',
            field=models.CharField(blank=True, choices=[('CHAIN', 'chain'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('FORM', 'form'), ('PHONE', 'phone'), ('TEXT', 'text'), ('CARDS', 'cards'), ('TITLE', 'title'), ('URL', 'url'), ('LOCATION', 'location'), ('MAIN', 'main')], max_length=300, null=True),
        ),
    ]
