# Generated by Django 4.0.5 on 2024-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0051_language_key_word_language_value_auto_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_info_details',
            name='template_button_type',
            field=models.CharField(blank=True, choices=[('URL', 'Url'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('LOCATION', 'location'), ('PHONE_NUMBER', 'Phone Number'), ('STOP', 'Stop'), ('FORM', 'form'), ('INFLOW', 'Inflow'), ('CAMPAIGN', 'Campaign')], max_length=300, null=True),
        ),
    ]
