# Generated by Django 4.0.5 on 2024-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0052_alter_template_info_details_template_button_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_customer_master',
            name='authorization_status',
            field=models.CharField(blank=True, choices=[('Done', 'DONE')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='campaign_customer_master',
            name='optin_status',
            field=models.CharField(blank=True, choices=[('No', 'NO')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generic_campaign_history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generic_campaign_history',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
