# Generated by Django 4.0.5 on 2024-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0053_campaign_customer_master_authorization_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_customer_master',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign_customer_master',
            name='otp_generated_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign_customer_master',
            name='otp_status',
            field=models.CharField(blank=True, choices=[('Verified', 'VERIFIED'), ('Unverified', 'UNVERIFIED')], max_length=40, null=True),
        ),
    ]
