# Generated by Django 4.0.5 on 2024-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0054_campaign_customer_master_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_cards',
            name='carousel_button1_type',
            field=models.CharField(blank=True, choices=[('URL', 'Url'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('LOCATION', 'location'), ('PHONE_NUMBER', 'Phone Number'), ('STOP', 'Stop'), ('FORM', 'form'), ('INFLOW', 'Inflow'), ('CAMPAIGN', 'Campaign')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='carousel_cards',
            name='carousel_button2_type',
            field=models.CharField(blank=True, choices=[('URL', 'Url'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('LOCATION', 'location'), ('PHONE_NUMBER', 'Phone Number'), ('STOP', 'Stop'), ('FORM', 'form'), ('INFLOW', 'Inflow'), ('CAMPAIGN', 'Campaign')], max_length=300, null=True),
        ),
    ]
