# Generated by Django 4.0.5 on 2024-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0056_pre_inflow_settings_languagepref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_customer_master',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='campaign_customer_master',
            name='preferred_language_status',
            field=models.CharField(blank=True, choices=[('Done', 'DONE')], max_length=40, null=True),
        ),
    ]
