# Generated by Django 4.0.5 on 2024-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0057_campaign_customer_master_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='short_description_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='short_title_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
