# Generated by Django 4.0.5 on 2024-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0058_inflow_setup_details_short_description_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_prepared_language',
            name='selected_language_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
