# Generated by Django 4.0.5 on 2024-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0059_user_prepared_language_selected_language_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='open_button_name_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
