# Generated by Django 4.0.5 on 2024-08-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0060_inflow_setup_details_open_button_name_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_body_footer_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='form_body_text_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='form_header_text_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='form_open_button_name_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='form_submit_button_name_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form_field',
            name='form_label_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form_fieldchoice',
            name='choice_text_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form_section',
            name='section_name_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inflow_setup_details',
            name='open_button_type',
            field=models.CharField(blank=True, choices=[('CHAIN', 'chain'), ('IMAGE', 'image'), ('VIDEO', 'video'), ('DOCUMENT', 'document'), ('FORM', 'form'), ('PHONE', 'phone'), ('TEXT', 'text'), ('CARDS', 'cards'), ('TITLE', 'title'), ('URL', 'url'), ('LOCATION', 'location'), ('MAIN', 'main'), ('ATM/BRANCH', 'ATM/Branch'), ('EMI_CALCULATOR', 'Emi Calculation'), ('INTEREST_CALCULATOR', 'Interest Calculator'), ('RD_CALCULATOR', 'RD Calculator'), ('ELIGIBILITY_CALCULATOR', 'Eligibility Calculatop'), ('SWP_CALCULATOR', 'SWP Calculator'), ('INFLATION_CALCULATOR', 'Inflation Calculatop'), ('FD_CALCULATOR', 'FD, Calculator'), ('SIP_CALCULATOR', 'SIP Calculatop')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='language_key',
            name='word',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='language_value',
            name='Value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='language_value',
            name='auto_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('client', 'marketplace', 'form_name'), name='unique_form'),
        ),
    ]
