# Generated by Django 4.0.5 on 2024-08-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_b', '0061_form_form_body_footer_key_form_form_body_text_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Preferred_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language_key', models.CharField(blank=True, max_length=100, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace')),
                ('preferred_language_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.language_value')),
            ],
        ),
        migrations.DeleteModel(
            name='User_Prepared_Language',
        ),
    ]
