# Generated by Django 4.0.5 on 2024-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0062_client_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_inflow_settings',
            name='default_translation',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('AUTO TRANSLATION', 'Auto Translation')], max_length=50, null=True),
        ),
    ]
