# Generated by Django 4.0.5 on 2024-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0064_alter_inflow_setup_details_open_button_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='active_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
