# Generated by Django 4.0.5 on 2024-08-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0065_inflow_setup_details_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow_setup_details',
            name='image_additional_file_path_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='inflow_body_text_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='inflow_footer_text_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inflow_setup_details',
            name='inflow_header_text_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
