# Generated by Django 4.0.5 on 2024-08-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0066_inflow_setup_details_image_additional_file_path_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_value',
            name='languages_file_path',
            field=models.FileField(blank=True, null=True, upload_to='language_file'),
        ),
        migrations.AddField(
            model_name='pre_inflow_settings',
            name='authorization_text_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pre_inflow_settings',
            name='choose_language_body_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pre_inflow_settings',
            name='choose_language_body_text_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pre_inflow_settings',
            name='verify_otp_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pre_inflow_settings',
            name='verify_otp_text_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
