# Generated by Django 4.2.3 on 2024-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0067_language_value_languages_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_inflow_settings',
            name='Preotp',
            field=models.CharField(blank=True, choices=[('no', 'Not Required'), ('required by email', 'REQUIRED BY EMAIL'), ('required by sms', 'REQUIRED BY SMS')], max_length=20, null=True),
        ),
    ]
