# Generated by Django 4.2.3 on 2024-08-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0068_alter_pre_inflow_settings_preotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_key',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('None', 'NONE'), ('pending', 'PENDING'), ('completed', 'COMPLETED')], max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='language_value',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('None', 'NONE'), ('pending', 'PENDING'), ('completed', 'COMPLETED')], max_length=90, null=True),
        ),
    ]
