# Generated by Django 4.2.3 on 2024-01-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0002_food_catalogue_hotel_rooms_type_room_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_catalogue',
            old_name='category_name',
            new_name='catalogue_discription',
        ),
        migrations.RenameField(
            model_name='room_list',
            old_name='room_room_type',
            new_name='hotel_room_type',
        ),
        migrations.AddField(
            model_name='food_catalogue',
            name='catalogue_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='food_catalogue',
            name='catalogue_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food_catalogue',
            name='catalogue_set_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
