# Generated by Django 4.2.3 on 2024-01-29 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_h', '0003_rename_category_name_food_catalogue_catalogue_discription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_services_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, choices=[('SERVICES', 'hotel services'), ('FOOD', 'food'), ('NEARBY', 'nearby place'), ('ROOM', 'room'), ('FACILITIES', 'hotel facilities'), ('SELP HELP', 'self help'), ('INFORMATION', 'Information')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('suport_number', models.IntegerField(blank=True, null=True)),
                ('control', models.CharField(blank=True, max_length=100, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
    ]
