# Generated by Django 4.2.3 on 2024-01-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0004_hotel_services_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='custom_number_0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='custom_number_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='custom_number_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='custom_number_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
