# Generated by Django 4.2.3 on 2024-02-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0005_food_custom_number_0_food_custom_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_services_settings',
            name='escalation_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel_services_settings',
            name='escalation_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
