# Generated by Django 4.2.3 on 2024-02-08 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_h', '0006_hotel_services_settings_escalation_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serivce_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone_num', models.IntegerField(blank=True, null=True)),
                ('customer_room', models.CharField(blank=True, max_length=100, null=True)),
                ('service_comments', models.CharField(blank=True, max_length=200, null=True)),
                ('service_status', models.CharField(blank=True, choices=[('REQUESTED', 'Requested'), ('ACKNOWLEDGED', 'Acknowledged'), ('COMPLETED', 'Completed')], max_length=100, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_services')),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='Food_order_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone_num', models.IntegerField(blank=True, null=True)),
                ('order_delivery_room', models.CharField(blank=True, max_length=200, null=True)),
                ('order_amount', models.IntegerField(blank=True, null=True)),
                ('order_comments', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('ORDERED', 'Ordered'), ('ACCEPTED', 'Accepted'), ('DELIVERED', 'Delivered')], max_length=100, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='Food_order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_quantity', models.IntegerField(blank=True, null=True)),
                ('Food_Item_Price', models.IntegerField(blank=True, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Food_Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.food')),
                ('Food_order_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.food_order_header')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
    ]
