# Generated by Django 4.2.3 on 2024-02-15 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_h', '0008_alter_food_order_header_customer_phone_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('Guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('GovernmentId', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Serivce_order',
            new_name='Service_order',
        ),
        migrations.AddField(
            model_name='hotel_rooms_type',
            name='room_availability',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Hotel_Room_Guest_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_In', models.DateTimeField(blank=True, null=True)),
                ('Check_Out', models.DateTimeField(blank=True, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Guest_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.guest_info')),
                ('Hotel_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_settings')),
                ('Room_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_rooms')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
    ]
