# Generated by Django 4.2.3 on 2024-02-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0009_guest_info_rename_serivce_order_service_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_room_guest_info',
            old_name='marketplace_id',
            new_name='marketplace',
        ),
        migrations.AddField(
            model_name='hotel_settings',
            name='Reception_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_room_guest_info',
            name='Room_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.room_list'),
        ),
    ]
