# Generated by Django 4.2.3 on 2024-03-14 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_h', '0011_checkout_questions_checkout_response_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_category', models.CharField(blank=True, max_length=400, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_comments', models.CharField(blank=True, max_length=400, null=True)),
                ('Complaint_status', models.CharField(blank=True, choices=[('REQUESTED', 'Requested'), ('ACKNOWLEDGED', 'Acknowledged'), ('COMPLETED', 'Completed')], max_length=100, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Complaint_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.complaint_settings')),
                ('Guest_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.guest_info')),
                ('Hotel_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_settings')),
                ('Room_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.room_list')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
