# Generated by Django 4.2.3 on 2024-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0014_rename_suport_number_hotel_services_settings_support_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_services_settings',
            name='support_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
