# Generated by Django 4.2.3 on 2024-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0016_remove_hotel_rooms_type_l_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_list',
            name='Hotel_room_image',
            field=models.ImageField(blank=True, null=True, upload_to='RoomImage'),
        ),
    ]
