# Generated by Django 4.2.3 on 2024-04-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0019_hotel_services_settings_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_settings',
            name='contact_one',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_settings',
            name='contact_three',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_settings',
            name='contact_two',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_settings',
            name='contact_us',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
