# Generated by Django 4.2.3 on 2024-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0020_alter_hotel_settings_contact_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_services',
            name='service_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
