# Generated by Django 4.2.3 on 2024-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0021_hotel_services_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_marketplace_settings',
            name='template_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel_marketplace_settings',
            name='template_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel_marketplace_settings',
            name='template_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
