# Generated by Django 4.0.5 on 2024-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0022_hotel_marketplace_settings_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_marketplace_settings',
            name='checkin_flow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel_marketplace_settings',
            name='checkout_flow_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
