# Generated by Django 4.0.5 on 2024-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0023_hotel_marketplace_settings_checkin_flow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby_place',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
