# Generated by Django 4.0.5 on 2024-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0024_nearby_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_room_guest_info',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nearby_place',
            name='address',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
