# Generated by Django 4.0.5 on 2024-06-19 10:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_h', '0025_hotel_room_guest_info_actual_check_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(blank=True, max_length=300, null=True)),
                ('message_header_text', models.CharField(blank=True, max_length=300, null=True)),
                ('message_header_image', models.ImageField(blank=True, null=True, upload_to='HotelNotificationImage')),
                ('message_header_video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('message_body', models.CharField(blank=True, max_length=1024, null=True)),
                ('message_header_type', models.CharField(choices=[('NONE', 'none'), ('IMAGE', 'image'), ('TEXT', 'text'), ('VIDEO', 'Video')], default='none', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='none', max_length=255)),
                ('message_footer', models.CharField(blank=True, max_length=300, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Guest_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.guest_info')),
                ('Hotel_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.hotel_settings')),
                ('Room_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.room_list')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_h.notification_message')),
            ],
        ),
    ]
