# Generated by Django 4.0.5 on 2024-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0026_notification_message_notification_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_message',
            old_name='message_header_image',
            new_name='image_message',
        ),
        migrations.RenameField(
            model_name='notification_message',
            old_name='message_body',
            new_name='text_message',
        ),
        migrations.RenameField(
            model_name='notification_message',
            old_name='message_header_video',
            new_name='video_message',
        ),
        migrations.RemoveField(
            model_name='notification_message',
            name='message_footer',
        ),
        migrations.RemoveField(
            model_name='notification_message',
            name='message_header_text',
        ),
        migrations.RemoveField(
            model_name='notification_message',
            name='message_header_type',
        ),
        migrations.AddField(
            model_name='notification_message',
            name='message_type',
            field=models.CharField(choices=[('IMAGE', 'image'), ('TEXT', 'text'), ('VIDEO', 'Video')], default='none', max_length=100),
        ),
    ]
