# Generated by Django 4.0.5 on 2024-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0028_alter_hotel_services_settings_escalation_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_settings',
            name='checkin_confirmation_message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hotel_settings',
            name='checkin_toolkit',
            field=models.FileField(blank=True, null=True, upload_to='hotel_checkin_toolkit'),
        ),
    ]
