# Generated by Django 4.0.5 on 2024-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0029_hotel_settings_checkin_confirmation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_settings',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
