# Generated by Django 4.0.5 on 2024-07-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0030_hotel_settings_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_marketplace_settings',
            old_name='template_id',
            new_name='conversation_activation_message_template_id',
        ),
        migrations.RenameField(
            model_name='hotel_marketplace_settings',
            old_name='template_name',
            new_name='conversation_activation_message_template_name',
        ),
        migrations.RenameField(
            model_name='hotel_marketplace_settings',
            old_name='template_status',
            new_name='conversation_activation_message_template_status',
        ),
        migrations.AddField(
            model_name='hotel_room_guest_info',
            name='Comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel_services_settings',
            name='last_escalation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel_services_settings',
            name='last_message_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel_settings',
            name='last_message_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
