# Generated by Django 4.0.5 on 2024-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0031_rename_template_id_hotel_marketplace_settings_conversation_activation_message_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_marketplace_settings',
            name='multiple_hotel_checkin_specific_flow_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
