# Generated by Django 4.0.5 on 2024-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0032_hotel_marketplace_settings_multiple_hotel_checkin_specific_flow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_settings',
            name='hotel_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Image'),
        ),
        migrations.AddField(
            model_name='hotel_settings',
            name='qr_hotel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
