# Generated by Django 4.0.5 on 2024-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0034_hotel_services_settings_last_activation_message_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_services_settings',
            name='last_escalation_message_datetime',
        ),
        migrations.AddField(
            model_name='complaint_info',
            name='last_escalation_message_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food_order_header',
            name='last_escalation_message_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_order',
            name='last_escalation_message_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
