# Generated by Django 4.0.5 on 2024-08-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0035_remove_hotel_services_settings_last_escalation_message_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_services_settings',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel_settings',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
