# Generated by Django 4.0.5 on 2024-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_h', '0036_hotel_services_settings_country_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_services_settings',
            old_name='country_code',
            new_name='escalation_number_country_code',
        ),
        migrations.AddField(
            model_name='hotel_services_settings',
            name='support_number_country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
