# Generated by Django 4.2.3 on 2023-07-18 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclientname', models.CharField(blank=True, max_length=200, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('re_password', models.CharField(max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'emailid')},
            },
        ),
        migrations.AlterField(
            model_name='admin_permission',
            name='billing_currency',
            field=models.CharField(choices=[('INR', 'Rupees'), ('USD', 'DOLLAR'), ('GBP', 'Pounds'), ('EUR', 'Euros')], default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment_gateway_details',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'Rupees'), ('USD', 'DOLLAR'), ('GBP', 'Pounds'), ('EUR', 'Euros')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SubUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.BooleanField(default=False)),
                ('ticket', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vailodb.subclient')),
            ],
            options={
                'unique_together': {('client', 'subclient')},
            },
        ),
    ]
