# Generated by Django 4.2.3 on 2023-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0002_subclient_alter_admin_permission_billing_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_settings',
            old_name='use_button_name',
            new_name='contact_button_name',
        ),
        migrations.RenameField(
            model_name='event_settings',
            old_name='use_header_image',
            new_name='contact_header_image',
        ),
        migrations.RenameField(
            model_name='event_settings',
            old_name='use_message_text',
            new_name='contact_message_text',
        ),
        migrations.AddField(
            model_name='event_settings',
            name='transfer_ticket',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='subuserpreference',
            name='scanner',
            field=models.BooleanField(default=False),
        ),
    ]
