# Generated by Django 4.2.3 on 2023-08-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0003_rename_use_button_name_event_settings_contact_button_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuserpreference',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='subuserpreference',
            name='scanner',
        ),
        migrations.RemoveField(
            model_name='subuserpreference',
            name='ticket',
        ),
        migrations.AddField(
            model_name='subuserpreference',
            name='preference',
            field=models.CharField(blank=True, choices=[('none', 'NONE'), ('ticket', 'TICKET'), ('scanner', 'SCANNER'), ('campaign', 'CAMPAIGN')], max_length=300, null=True),
        ),
    ]
