# Generated by Django 4.2.3 on 2023-08-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0006_alter_subuserpreference_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_billing_details',
            name='transaction_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
