# Generated by Django 4.2.3 on 2023-09-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0007_ticket_billing_details_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_permission',
            name='client_service_type',
            field=models.CharField(choices=[('commerce', 'COMMERCE'), ('ticket', 'TICKET'), ('scanner', 'SCANNER'), ('donation', 'DONATION'), ('appointement', 'APPOINTEMENT')], default='none', max_length=200),
        ),
    ]
