# Generated by Django 4.2.3 on 2023-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0009_alter_admin_permission_client_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_permission',
            name='client_marketplace',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='none', max_length=200),
        ),
    ]
