# Generated by Django 4.2.3 on 2023-12-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0010_admin_permission_client_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuserpreference',
            name='marketplace_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
