# Generated by Django 4.2.3 on 2023-12-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0011_subuserpreference_marketplace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_details',
            name='fb_Whatsapp_business_account_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
