# Generated by Django 4.2.3 on 2024-01-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0012_facebook_details_fb_whatsapp_business_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_permission',
            name='client_service_type',
            field=models.CharField(choices=[('commerce', 'COMMERCE'), ('ticket', 'TICKET'), ('scanner', 'SCANNER'), ('donation', 'DONATION'), ('appointement', 'APPOINTEMENT'), ('survey', 'SURVEY'), ('hotel', 'HOTEL')], default='none', max_length=200),
        ),
    ]
