# Generated by Django 4.2.3 on 2024-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0014_alter_admin_permission_client_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuserpreference',
            name='history_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
