# Generated by Django 4.2.3 on 2024-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0015_subuserpreference_history_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_details',
            name='private_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='facebook_details',
            name='public_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
