# Generated by Django 4.2.3 on 2024-02-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0018_facebook_details_dynamic_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook_details',
            old_name='dynamic_file_name',
            new_name='private_dynamic_file_name',
        ),
        migrations.AddField(
            model_name='facebook_details',
            name='public_dynamic_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
