# Generated by Django 4.2.3 on 2024-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0019_rename_dynamic_file_name_facebook_details_private_dynamic_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_details',
            name='fb_catalogId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
