# Generated by Django 4.2.3 on 2024-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0020_facebook_details_fb_catalogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_details',
            name='fb_app_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
