# Generated by Django 4.0.5 on 2024-07-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb', '0023_rename_history_preference_subuserpreference_menu_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_permission',
            name='client_service_type',
            field=models.CharField(choices=[('commerce', 'COMMERCE'), ('ticket', 'TICKET'), ('scanner', 'SCANNER'), ('donation', 'DONATION'), ('appointement', 'APPOINTEMENT'), ('survey', 'SURVEY'), ('hotel', 'HOTEL'), ('campaign', 'CAMPAIGN'), ('malls', 'MALLS'), ('banking', 'BANKING')], default='none', max_length=200),
        ),
    ]
