# Generated by Django 4.0.5 on 2024-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_f', '0002_banking_configuration_marketplace_branch_atm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_atm',
            name='PIN_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
