# Generated by Django 4.0.5 on 2024-08-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_f', '0003_alter_branch_atm_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_atm',
            name='pin_code_flow_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch_atm',
            name='vailo_record_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='branch_atm',
            name='vailo_record_last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='branch_atm',
            name='vailo_record_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
