# Generated by Django 4.0.5 on 2024-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_f', '0004_branch_atm_pin_code_flow_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_atm',
            name='pin_code_flow_id',
        ),
        migrations.AddField(
            model_name='banking_configuration',
            name='pin_code_flow_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
