# Generated by Django 4.0.5 on 2024-08-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_b', '0064_alter_inflow_setup_details_open_button_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_f', '0007_rename_calcalation_banking_configuration_calculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banking_configuration',
            old_name='calculation',
            new_name='calculator_status',
        ),
        migrations.RemoveField(
            model_name='banking_configuration',
            name='pin_code_flow_id',
        ),
        migrations.CreateModel(
            name='Banking_Calculators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_Code', models.CharField(blank=True, max_length=500, null=True)),
                ('calculator_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('calculator_FlowID', models.CharField(blank=True, max_length=500, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True, null=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_b.campaign_marketplace')),
            ],
        ),
    ]
