# Generated by Django 4.0.5 on 2024-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_f', '0008_rename_calculation_banking_configuration_calculator_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking_configuration',
            name='atm_branch_pincode_flowid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banking_configuration',
            name='atm_branch_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
