# Generated by Django 4.2.3 on 2023-10-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_list',
            name='flow_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='survey_question',
            name='Survey_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_s.survey_list'),
        ),
        migrations.AddField(
            model_name='survey_question',
            name='question_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Survey_Question_Mapping',
        ),
    ]
