# Generated by Django 4.2.3 on 2024-01-11 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_s', '0004_survey_marketplace_survey_types_survey_categorys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_marketplace',
            name='survey_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='survey_marketplace',
            name='survey_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='survey_marketplace',
            name='survey_link_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='survey_marketplace',
            name='survey_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Survey_marketplace_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('my_survey_flow_id', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplace_welcome_image', models.ImageField(blank=True, null=True, upload_to='FlowImage')),
                ('marketplace_welcome_message_body', models.CharField(blank=True, max_length=500, null=True)),
                ('marketplace_welcome_message_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('generic_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('specific_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mysurvey_flow_cta_name', models.CharField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
