# Generated by Django 4.2.3 on 2024-05-02 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_m', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mall_services_settings',
            new_name='Mall_services_setting',
        ),
    ]
