# Generated by Django 4.2.3 on 2024-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_m', '0002_rename_mall_services_settings_mall_services_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shop_category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mall_services_setting',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
