# Generated by Django 4.2.3 on 2024-05-07 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_m', '0003_restaurant_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_responses',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_m.mall_marketplace'),
        ),
        migrations.CreateModel(
            name='Key_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='Image')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('availability', models.CharField(blank=True, choices=[('Yes', 'YES'), ('No', 'NO')], max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('EUR', 'Euros'), ('GBP', 'British Pound'), ('INR', 'Indian Rupees'), ('USD', 'US Dollar')], max_length=100, null=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_m.mall_marketplace')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_m.restaurant')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_m.shop')),
            ],
        ),
    ]
