# Generated by Django 4.1.5 on 2024-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_m', '0004_feedback_responses_marketplace_key_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='malls_marketplace_settings',
            name='template_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='malls_marketplace_settings',
            name='template_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='malls_marketplace_settings',
            name='template_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
