# Generated by Django 4.0.5 on 2024-08-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_m', '0005_malls_marketplace_settings_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_category',
            name='restaurant_parent_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_category',
            name='restaurant_reference_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shop_category',
            name='shop_parent_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shop_category',
            name='shop_reference_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mall_services_setting',
            name='key',
            field=models.CharField(blank=True, choices=[('Shopping', 'SHOPPING'), ('Movies', 'MOVIES'), ('Parking', 'PARKING'), ('Restaurant', 'RESTAURANT'), ('Funzone', 'FUNZONE'), ('Events', 'EVENTS'), ('Information', 'INFORMATION'), ('Feedback', 'FEEDBACK'), ('Offers', 'OFFERS')], max_length=100, null=True),
        ),
    ]
