# Generated by Django 4.1.5 on 2024-08-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vailodb_m', '0007_events_body_text_events_button_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='mall_services_setting',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='mall_services_setting',
            name='button_name',
        ),
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_m.mall_marketplace')),
            ],
        ),
    ]
