# Generated by Django 4.2.3 on 2023-09-08 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(blank=True, max_length=500, null=True)),
                ('consultant_photo', models.ImageField(blank=True, null=True, upload_to='ConsultantPhoto')),
                ('consultant_image', models.ImageField(blank=True, null=True, upload_to='ConsultantImage')),
                ('consultant_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('consultant_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('slot_duration', models.CharField(blank=True, max_length=300, null=True)),
                ('consultant_specialization', models.CharField(blank=True, max_length=300, null=True)),
                ('consultant_timezone', models.CharField(blank=True, max_length=300, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Visitor_Whatsapp_Number', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_City', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_Address_Line1', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_Address_Line2', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_Address_Landmark', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_Address_Pincode', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_State', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_Country', models.CharField(blank=True, max_length=300, null=True)),
                ('Visitor_Phone_Number', models.CharField(blank=True, max_length=300, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Main_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_image', models.ImageField(blank=True, null=True, upload_to='ConsultantWelcomeImage')),
                ('welcome_message', models.CharField(blank=True, max_length=500, null=True)),
                ('booking_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('my_bookings_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_us_button_name', models.CharField(blank=True, max_length=500, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday_leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Consultant_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_a.consultant_settings')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('online_offline', models.CharField(blank=True, max_length=300, null=True)),
                ('notes1', models.CharField(blank=True, max_length=300, null=True)),
                ('notes2', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Consultant_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_a.consultant_settings')),
                ('Visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_a.visitor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availablity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('vailo_record_creation', models.DateTimeField(auto_now_add=True)),
                ('vailo_record_last_update', models.DateTimeField(auto_now=True)),
                ('vailo_record_status', models.IntegerField(blank=True, null=True)),
                ('Consultant_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vailodb_a.consultant_settings')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
