# Generated by Django 4.2.3 on 2023-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0003_alter_consultant_settings_consultant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant_settings',
            name='consultant_support_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='main_settings',
            name='consultant_list_button_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='main_settings',
            name='consultant_list_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='main_settings',
            name='main_support_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
