# Generated by Django 4.2.3 on 2023-09-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0004_consultant_settings_consultant_support_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
