# Generated by Django 4.2.3 on 2023-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0005_rename_time_bookings_end_time_bookings_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_reference_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
