# Generated by Django 4.2.3 on 2023-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0006_bookings_booking_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
