# Generated by Django 4.2.3 on 2023-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0007_bookings_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant_settings',
            name='approval_mode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
