# Generated by Django 4.2.3 on 2023-10-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0008_consultant_settings_approval_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_settings',
            name='contactus_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='main_settings',
            name='contactus_image',
            field=models.ImageField(blank=True, null=True, upload_to='ContactUsImage'),
        ),
    ]
