# Generated by Django 4.2.3 on 2023-10-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0009_main_settings_contactus_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_settings',
            name='contactus_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
