# Generated by Django 4.2.3 on 2023-11-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0010_main_settings_contactus_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant_settings',
            name='consultant_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consultant_settings',
            name='consultant_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
