# Generated by Django 4.2.3 on 2024-01-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vailodb_a', '0014_appointment_marketplace_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_marketplace',
            name='appointment_link_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment_marketplace',
            name='appointment_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment_marketplace',
            name='group_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment_marketplace',
            name='group_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment_settings',
            name='appointment_link_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='appointment_settings',
            name='appointment_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
